version: '3.9'
services:
  postgresql:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  migration:
    image: express-prisma-template-migration:latest
    build: 
      context: .
      dockerfile: Dockerfile.migration
      args:
        GIT_ACCESS_KEY: ${GIT_ACCESS_KEY}
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/express_prisma_template?schema=public

      - WAIT_HOSTS=postgresql:5432
      - WAIT_SLEEP_INTERVAL=5
  ci:
    image: express-prisma-template-ci:latest
    build: 
      context: .
      dockerfile: Dockerfile.ci
      args:
        GIT_ACCESS_KEY: ${GIT_ACCESS_KEY}
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/express_prisma_template?schema=public

      - WAIT_HOSTS=migration:80
      - WAIT_SLEEP_INTERVAL=5
    volumes:
      - ./coverage:/usr/src/app/coverage
  app:
    image: express-prisma-template:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        GIT_ACCESS_KEY: ${GIT_ACCESS_KEY}
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/express_prisma_template?schema=public
      - PORT=3000

      - WAIT_HOSTS=ci:80
      - WAIT_SLEEP_INTERVAL=5
    ports:
      - 3000:3000
