version: '3.9'
services:
  postgresql:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  # postgresql:
  #   image: postgres:13.2
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - /Users/reynandaptr/Development/docker/postgresql:/var/lib/postgresql/data
  migration:
    image: ghcr.io/reynandaptr/express-prisma-migration:latest
    pull_policy: always
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/express_prisma_test?schema=public

      - WAIT_HOSTS=postgresql:5432
      - WAIT_SLEEP_INTERVAL=5
